[package]
name = "rspass"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
crossterm = "0.28.1"
rspass-core = { path = "../rspass-core" }
